name: "pi-pr-review"
description: "Run pi in CI to generate a PR review (comment-only) with inline comments + summary"

inputs:
  pi-version:
    description: "npm version/range for @mariozechner/pi-coding-agent"
    required: false
    default: "latest"
  provider:
    description: "pi provider (e.g. openrouter)"
    required: false
    default: "openrouter"
  model:
    description: "model id for the provider"
    required: false
    default: "minimax/minimax-m2.1"
  max-comments:
    description: "Max inline comments to post"
    required: false
    default: "20"

runs:
  using: node20
  main: index.js
